# Generated by Django 4.0 on 2022-05-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True, verbose_name='User ID')),
                ('user_pw', models.CharField(max_length=128, verbose_name='user password')),
                ('user_name', models.CharField(max_length=16, unique=True, verbose_name='User Name')),
                ('user_email', models.CharField(max_length=128, unique=True, verbose_name='User Email')),
                ('user_register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Account Created Datetime')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 'user',
            },
        ),
    ]
